kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "fwb-k8s-ctrl.serviceAccountName" . }}
rules:
- apiGroups: [""]
  resources: ["pods", "services", "nodes", "endpoints", "secrets"]
  verbs: ["get", "watch", "list", "update"]
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - networking.k8s.io
  resources:
  - ingressclasses
  verbs:
  - get
  - list
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses/status
  verbs:
  - update
- apiGroups:
  - extensions
  resources:
  - ingresses/status
  verbs:
  - update
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "fwb-k8s-ctrl.serviceAccountName" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "fwb-k8s-ctrl.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "fwb-k8s-ctrl.serviceAccountName" . }}
  apiGroup: rbac.authorization.k8s.io
