apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "fwb-k8s-ctrl.fullname" . }}
  labels:
    {{- include "fwb-k8s-ctrl.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "fwb-k8s-ctrl.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "fwb-k8s-ctrl.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
      #    {{- if eq .Values.parameters.openshiftRouteSupport "yes" }}
      #    securityContext:
      #        allowPrivilegeEscalation: false
      #        runAsNonRoot: true
      #        seccompProfile:
      #            type: RuntimeDefault
      #        capabilities:
      #            drop: ["ALL"]
      #    {{- end }}

      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
