apiVersion: v1
kind: Node
metadata:
  name: fad
  labels:
    topology.kubernetes.io/zone: "fake-node"
  annotations:
    #Replace public-ip with outgoing interface IP of overlay tunnel
    flannel.alpha.coreos.com/public-ip: "172.23.133.148"
    #Replace VtepMAC with your VXLAN interface MAC
    flannel.alpha.coreos.com/backend-data: '{"VNI":1,"VtepMAC":"B4:F0:AB:E9:F4:DC"}'
    flannel.alpha.coreos.com/backend-type: "vxlan"
    flannel.alpha.coreos.com/kube-subnet-manager: "true"
spec:
  podCIDR: "10.244.30.0/24"
