kind: Pod
apiVersion: v1
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  containers:
  - name: nginx
    image: nginx
---
kind: Service
apiVersion: v1
metadata:
  labels:
  name: default-http-backend
  namespace: default
  annotations: {
    "health-check-ctrl" : "HLTHCK_ICMP",
    "lb-algo" : "round-robin",
  }
spec:
  type: NodePort
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx
  sessionAffinity: None

